### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by n-erinq** [n-erinq/DontForgetQuest#24]
### 概要
Issueベース作成しましたのでご確認のほどお願いいたします。

### 実装予定の機能
MVPリリース
- [ ] ユーザ登録・編集機能
- [ ] 認証ログイン機能
- [ ] アワード新規登録・編集・削除機能
- [ ] チェックリスト新規登録・編集・削除機能
- [ ] チェック記録機能
- [ ] 達成記録保存機能

本リリース
- [ ] ゲストユーザー機能
- [ ] LINE通知機能(プッシュ通知)
- [ ] 気象情報機能

### 必要なページ
- [ ] トップページ
- [ ] サービス説明画面
- [ ] ユーザ新規登録・編集画面
- [ ] ログイン画面
- [ ] アワード新規登録・編集画面
- [ ] チェックリスト新規登録・編集画面
- [ ] 達成記録閲覧画面
- [ ] 利用規約・プライバシーポリシー・お問合せ画面

**Comment by kenchasonakai** [comment]
LGTMです！
